language: python
python:
- '3.4'
- '3.5'
- '3.6'
sudo: enabled
addons:
  apt:
    packages:
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin
    - libhdf5-serial-dev
    - gfortran
install:
- source continuous_integration/install.sh
- pip install .
- pip install pytest
script: pytest
deploy:
  provider: pypi
  user: alejoe91
  on:
    tags: true
  password:
    secure: uZWVtNF3cH9wREbeIZzOTxioX6JICQl3OWD6cl/lW3vwZdsF49cybJyWIvcfe8Ou848gUfxkUIJuAriPMe06WgP1qKdDPEIyxnNQnYB0/Cl37ePTs1jVLOrkZ5v4ynJPWCitMDw4IhcFHN7dfjemOFNdAFKI8sxxkZ1tL1P2PtiAklZLeuJhR+Tt2pYMyl+E2ZousHyH80ulUA/blPoQ5macntaD8Zp9B+ipI8RY3D+4L+IPoIHy/Em7EiFEZE99XuX5zTbm/905/Ha20USbZ8ZCUdSo7dn7TQftjjoBlJDjzSZhiSppJmBeO7BNdyl6lhNlcy7ERFJ0r/o6juXFcN9AFB+L8wqe7Vz6wsuF6Mv3q3h2KEuIgoMzj77pSFn945My4+Pc+XdCHvmVcWSdeqd2Fp5yHHpzI8lBlXIKW6FtnzERZDcRYV67RbY9dGUCt9klz/smAJneGj4OLJbY0c7ViRsKk/Fv8iujQhnevwrVmCZhySzQUGQNLW91dPqoM5cdjfIazln8uPCVNxd0u32rLUkAzvUp+WwDW8bQ7GrM6ok3DnbiGIZdrY8G34im/d0PScX2bPgzjWw5MGPaXsOm4scHHqZmSp9u6vdov24yyoCmhGXOeXGeDOWvluzOuxCSxovVGbOV7+wCMN4pNA/kMmoXVbptxBO6d3jHA7I=
