language: python
python:
- '3.6'
sudo: enabled
addons:
  apt:
    packages:
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin
    - libhdf5-serial-dev
    - gfortran
install:
- source continuous_integration/install.sh
- pip install matplotlib
- pip install LFPy
- pip install .
- pip install pytest
script: py.test -s
deploy:
  provider: pypi
  user: alejoe91
  on:
    branch: master
    tags: true
  password:
    secure: KOP/J29wJHUyeWyE/r4Hn2Z5N74/YFhLG4P4VUnc++YcSBVIurNsR6cLWmUtjxvHEFK1uLFDsQA8rJeolzLxewUYylPZ7YRPCDqOucfeFHnoG2RY9A9D4RUv+cppHvunKDltCeq/CzBtH8ST1U/+/zA/XuSUtBb4FKLREkqv3b2UhecD/43vHmNCOb4deQZ3BXLY7ReRIQGssEj9G4d+4Z9cp065f+Etw0X/fBwueOEkCdmi2pJXdEr/Fr+vRqPIhUxJri9HaPML/xJ5nKN33x1xoukz66MAhARwgCa9rymjaGRyc1dWHMn+21dhhYJhffXLwInCMaY+cZDhbuZ5rxoFuvgH07TJ9nQzr63nLBt+lcIxtmGsOiaimutfkW8ZL/GExA5kgZcjfRiMJzqTc3CNkLCp9gaHTeye/2q1K4L5Z/+bdmhC7JCeaSy30pjLKlvkXWVJKTbVF45W0tderOlFTsb84nrVeijCO/TYjmX6UB342Sk7HPmGpkPxwCFkvB6dxpZC9HOEE64D34YI5iRQY06YazfYscDCVFJ/7ob1SSGVN6clutKf17p+4hS+FbjUm1Sfc+fHnMUyGRXt9KsnHZhRQnZDKNoiJZhER1ySexiTea+1+Arsm6gyJM2pFCrKKBQbHZ2VyaSoi26rtce7qcifuF0oAYa5gssqhCE=
