language: python
python:
- '3.6'
sudo: enabled
addons:
  apt:
    packages:
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin
    - libhdf5-serial-dev
    - gfortran
install:
- source continuous_integration/install.sh
- pip install matplotlib
- pip install LFPy
- pip install .
- pip install pytest
script: py.test -s
deploy:
  provider: pypi
  user: alejoe91
  on:
    tags: true
  password:
    secure: HAWGHeP0EgN+hIP6AvilpeLjVfy5SS9qk8Rg7utVweKP+ZxA00A+Y3CBe18TF0FWrTwaeAg40HDVDCuo0FPRydfT4TSdxemD4YD8ogQ08xvU/6hDwNofRi48FGqqz0+qO0RMhy8eNacCWXt80YEDVzY0+ZiItCC2+MPf1glAJglExUfIlFW14Wz+Slzu3lAh+v4y8vTCP9xPeCXT9MXBS9J32yn0DcilAAK/oCIoqtXD+iAz9w1x6lhRqttFqioqnTVWiQ1u41YjrQ1ZO00uRntbVpHHDoqrRg5JlQ4ugmJs7E1rrIj9bX6ybd4x+y4kZbxrWOj30ljuOpNJvzSFS3TMNPP8JjBGrej2g21MYs6t9o1L0Y+UkqmBUDrLG3wxyHo/UVwMGfik8cnznB2FAGem7Z5acxzXEH6SOuwvRl7R+1NYf/rResQEnkmxj9dPpE+k1B0Dqgc3YVFXDaFyG4yLgUkYRTYs4Hsw1qIOHSjEIWhgvkv4osueyAAgBcvxKbVZAy2PudCuvbQ9G9ge5USqSs5ZSr/xsbSa586cm8gmHglD06NlrbxhBkxocRc7F3D++c42LRVSX4zWCIxG6AhcuZDVe/USC8B8npX08/o/36so6mR16HGlPB/qq2wCc/3FzfB7AjSmjtQSgf2q76qe4GZwQbJDpToWMegqB4c=
